package com.faniot.platform.gateway.vo;

import com.faniot.platform.gateway.domain.Gateway;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

@Schema(description = "盒子信息")
public record GatewayVO(
        Long id,
        String gatewayId,
        String gatewaySn,
        String gatewayName,
        String gatewayModel,
        String imei,
        String iccid,
        String simCardNo,
        String customerId,
        String customerName,
        String projectId,
        String projectName,
        String activationStatus,
        String onlineStatus,
        String mqttClientId,
        String mqttUsername,
        String publishTopic,
        String subscribeTopic,
        String mqttVersion,
        Integer qos,
        Integer keepalive,
        Boolean tlsEnabled,
        Boolean remoteConfigSupported,
        OffsetDateTime lastConfigTime,
        String firmwareVersion,
        BigDecimal latitude,
        BigDecimal longitude,
        String address,
        String province,
        String city,
        String district,
        String locationSource,
        OffsetDateTime locationUpdatedAt,
        OffsetDateTime lastLocationTime,
        Integer lbsMcc,
        Integer lbsMnc,
        Long lbsLac,
        Long lbsCid,
        Integer lbsAccuracy,
        OffsetDateTime lastSeenAt,
        String remark,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {
    public static GatewayVO from(Gateway gateway, String customerName, String projectName) {
        return new GatewayVO(
                gateway.getId(),
                gateway.getGatewayId(),
                gateway.getGatewaySn(),
                gateway.getGatewayName(),
                gateway.getGatewayModel(),
                gateway.getImei(),
                gateway.getIccid(),
                gateway.getSimCardNo(),
                gateway.getCustomerId(),
                customerName,
                gateway.getProjectId(),
                projectName,
                gateway.getActivationStatus(),
                gateway.getOnlineStatus(),
                gateway.getMqttClientId(),
                gateway.getMqttUsername(),
                gateway.getPublishTopic(),
                gateway.getSubscribeTopic(),
                gateway.getMqttVersion(),
                gateway.getQos(),
                gateway.getKeepalive(),
                gateway.getTlsEnabled(),
                gateway.getRemoteConfigSupported(),
                gateway.getLastConfigTime(),
                gateway.getFirmwareVersion(),
                gateway.getLatitude(),
                gateway.getLongitude(),
                gateway.getAddress(),
                gateway.getProvince(),
                gateway.getCity(),
                gateway.getDistrict(),
                gateway.getLocationSource(),
                gateway.getLocationUpdatedAt(),
                gateway.getLastLocationTime(),
                gateway.getLbsMcc(),
                gateway.getLbsMnc(),
                gateway.getLbsLac(),
                gateway.getLbsCid(),
                gateway.getLbsAccuracy(),
                gateway.getLastSeenAt(),
                gateway.getRemark(),
                gateway.getCreatedAt(),
                gateway.getUpdatedAt()
        );
    }
}
